repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.2
    hooks:
      - id: terraform_fmt
        files: \.tf$
        pass_filenames: false
      - id: terraform_validate
        pass_filenames: false
      - id: terraform_tflint
        pass_filenames: false

  - repo: local
    hooks:
      - id: build-and-push-new-ecr-docker-images
        name: Build and Push New ECR Docker Images
        entry: ecr-scripts/build-and-push-lambda-artifacts.sh
        language: script
